# Generated by Django 5.1.2 on 2024-11-24 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timewindow',
            name='availability',
        ),
        migrations.AlterField(
            model_name='kids',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kids',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('babysitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babysitter', to='base.babysitter')),
            ],
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='TimeWindow',
        ),
    ]
