# Generated by Django 5.1.2 on 2024-11-24 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_timewindow_availability_alter_kids_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='babysitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='base.babysitter'),
        ),
    ]
